# mall-ware
server:
  port: 11000

spring:
  datasource:
    url: jdbc:mysql://39.108.11.141:3306/meec_wms
    username: root
    password: elricchen0710!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  #  默认 >> classpath*:/mapper/**/*.xml (classpath*：表示包含依赖的类路径下)
  mapper-locations: classpath:/mapper/**/*.xml
  #  目前ID自增，等后面分库分表在修改
  global-config:
    db-config:
      id-type: auto